const eventSlidesDataApi=[
    {
        id:1,
        slideText:"slide1",
        imgSrc:"https://e0.pxfuel.com/wallpapers/6/451/desktop-wallpaper-hi-tech-ultra-high-resolution-tech.jpg"
    },
    {
        id:2,
        slideText:"slide2",
        imgSrc:"http://thestatetimes.com/wp-content/uploads/2018/02/infotech.jpg"
    },
    {
        id:3,
        slideText:"slide3",
        imgSrc:"https://source.unsplash.com/1600x900/?technology"
    },
    {
        id:4,
        slideText:"slide4",
        imgSrc:"https://source.unsplash.com/1600x900/?technology"
    },
    {
        id:5,
        slideText:"slide5",
        imgSrc:"https://wallpapercave.com/wp/ngPEfyE.jpg"
    },
    {
        id:6,
        slideText:"slide6",
        imgSrc:"http://thestatetimes.com/wp-content/uploads/2018/02/infotech.jpg"
    },
    {
        id:7,
        slideText:"slide7"
    },
    {
        id:8,
        slideText:"slide8"
    }
]
export default eventSlidesDataApi